### PR TITLE
gh-116 Correctly compile and fix Hazelcast2CacheMetrics

### LINKED ISSUE #116: Prometheus endpoint raises ERROR when caching metrics enabled
Alfresco EE 5.2.1
Alfred Telemetry 0.5.2

2021-07-09 08:37:29,691 ERROR [org.springframework.extensions.webscripts.AbstractRuntime] [tomcat-exec-36] Exception from executeScript: com.hazelcast.monitor.LocalMapStats.getPutOperationCount()J

java.lang.NoSuchMethodError: com.hazelcast.monitor.LocalMapStats.getPutOperationCount()J

        at eu.xenit.alfred.telemetry.binder.cache.Hazelcast2CacheMetrics.putCount(Hazelcast2CacheMetrics.java:100)

        at io.micrometer.core.instrument.binder.cache.CacheMeterBinder.lambda$bindTo$3(CacheMeterBinder.java:77)

        at io.micrometer.core.instrument.cumulative.CumulativeFunctionCounter.count(CumulativeFunctionCounter.java:39)

        at io.micrometer.prometheus.PrometheusMeterRegistry.lambda$newFunctionCounter$6(PrometheusMeterRegistry.java:271)

        at io.micrometer.prometheus.MicrometerCollector.lambda$collect$0(MicrometerCollector.java:81)

        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)

        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)

        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)

        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)

        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)

        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)

        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)

        at io.micrometer.prometheus.MicrometerCollector.collect(MicrometerCollector.java:82)

        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.findNextElement(CollectorRegistry.java:183)

        at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:216)

       at io.prometheus.client.CollectorRegistry$MetricFamilySamplesEnumeration.nextElement(CollectorRegistry.java:137)

        at io.prometheus.client.exporter.common.TextFormat.write004(TextFormat.java:22)

        at io.micrometer.prometheus.PrometheusMeterRegistry.scrape(PrometheusMeterRegistry.java:75)

        at eu.xenit.alfred.telemetry.util.PrometheusRegistryUtil.extractPrometheusScrapeData(PrometheusRegistryUtil.java:31)

        at eu.xenit.alfred.telemetry.webscripts.PrometheusWebScript.executeInternal(PrometheusWebScript.java:56)

        at eu.xenit.alfred.telemetry.webscripts.PrometheusWebScript.execute(PrometheusWebScript.java:48)

        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:467)

        at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:656)

        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:355)

        at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:308)

        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:399)

        at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:210)

        at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)

        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)

        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)

        at org.alfresco.module.aosmodule.service.ContextRootFilter.doFilter(ContextRootFilter.java:93)

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)

        at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68)

        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)

        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)

        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)

        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:110)

        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:506)

        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:169)

        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)

        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)

        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:445)

        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1087)

        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:637)

        at org.apache.tomcat.util.net.AprEndpoint$SocketWithOptionsProcessor.run(AprEndpoint.java:2486)

        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

        at java.lang.Thread.run(Thread.java:748)

### PR DESCRIPTION
**Pull request by kerkhofsd**
Fixes #116

### CODE REVIEW

**Review by driesdeproost — APPROVED** [review]

**Comment by thijslemmens** [comment]
@kerkhofsd Shouldn't we add caching metrics to the smoke tests?

**Comment by driesdeproost** [comment]
build fails though

**Comment by kerkhofsd** [comment]
@thijslemmens problem is that this problem doesn't show in current integration testing setup, 

It requires a clustered Alfresco environment (including a valid license)...

**Comment by thijslemmens** [comment]
and a clustered setup is hard because of bootstrapping.

Op vr 9 jul. 2021 om 16:31 schreef Daan Kerkhofs ***@***.***>:

**Comment by kerkhofsd** [comment]
To avoid the need of reflection in `Hazelcast2CacheMetrics`, we now compile against and build with an older, fixed Hazelcast version (2.4). 
In new Alfresco versions, the OOTBox `HazelcastCacheMetrics`, included in Micrometer, is used anyway. 

Added some minimal tests for the `Hazelcast2CacheMetrics` class.

**Pull request merged**
