### PR TITLE
ALFREDOPS-270 Legacy system to support the licence metrics of care4Alf

### PR DESCRIPTION
**Pull request by JoostDeCupere**

### CODE REVIEW

**Review by kerkhofsd — APPROVED** [review]

**Review by thijslemmens — CHANGES_REQUESTED** [review]
I think you need to add `alfred.telemetry.binder.legacy-license-metrics.enabled=false` to the alfresco-global.properties to prevent the metrics from popping up by default.

**Comment by kerkhofsd** [comment]
@thijslemmens is correct. We need to include following default configuration:

- `alfred.telemetry.binder.care4alf.legacy-license-metrics.enabled=true` to enable the metric including the `application=care4alf` tag. This is because the `Care4AlfMeterBinderRegistrar` doesn't register metrics by default. 
- alfred.telemetry.binder.legacy-license-metrics.enabled=false to disable the default metric. This is because the `MeterBinderRegistrar` registers metrics by default.

**Comment by JoostDeCupere** [comment]
> @thijslemmens is correct. We need to include following default configuration:
> 
> * `alfred.telemetry.binder.care4alf.legacy-license-metrics.enabled=true` to enable the metric including the `application=care4alf` tag. This is because the `Care4AlfMeterBinderRegistrar` doesn't register metrics by default.
> * alfred.telemetry.binder.legacy-license-metrics.enabled=false to disable the default metric. This is because the `MeterBinderRegistrar` registers metrics by default.

- Added the properties but withouth the -metrics at the end, it does not seem to be needed but correct me if I'm wrong.

**Comment by thijslemmens** [comment]
There is a problem with the enterprise 61 Solr composeUp:
2021-07-07 06:04:47,415  ERROR [web.context.ContextLoader] [localhost-startStop-1] Context initialization failed
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'alfred-telemetry.Care4AlfMeterBinderRegistrar' defined in class path resource [alfresco/module/alfred-telemetry-platform/context/binder-context.xml]: Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter containing tag keys []. The meter you are attempting to register has keys [application].
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:845)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:400)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:291)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
	at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:70)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4689)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5155)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1125)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1858)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys. There is already an existing meter containing tag keys []. The meter you are attempting to register has keys [application].
...

	at eu.xenit.alfred.telemetry.binder.care4alf.LegacyLicenseMetrics.bindTo(LegacyLicenseMetrics.java:29)
	at eu.xenit.alfred.telemetry.binder.MeterBinderRegistrar.lambda$addBinders$0(MeterBinderRegistrar.java:57)

Complaining about 2 meters with the same name, but different tag set. 
It works on 5.2 . Are we using different micrometer versions in the 2 situations?

**Pull request closed without merging**
